version: '2'
services:
  nginx:
# 从本地Dockerfile进行build
    #build: ./build/nginx
# 此处为自定义nginx配置（文件名必须为*.conf），用于支持unknown.guanaitong.dev
    volumes:
      - ./local/my.conf:/etc/nginx/conf.d/my.conf
  php:
# 从本地Dockerfile进行build
    build: ./build/php
# 此处为自定义php配置（文件名必须为*.ini），用于开启未加载的扩展等
#    volumes:
#      - ./local/my.ini:/usr/local/etc/php/conf.d/my.ini:ro
# 此处为自定义webservice配置，用于使用本地webservice
#    extra_hosts:
#        - "nfshost:10.101.9.216"
#        - "messagepush.services.dev.ofc:192.168.99.100"
        
